### ISSUE TITLE
Delete image tag

### ISSUE THREAD

**Issue by nlamirault** [genuinetools/reg#100]
Hi, 
it is possible to delete a tag from a Docker image ?

**Comment by DmitriyMurzin** [comment]
No( Apparently this is a bug, because I can not remove the image, even though the permission in registry.

**Comment by jstoja** [comment]
No, it's not possible and it's not a bug.
For now, only digest deletion is supported (which is the simplest implementation of the docker registry's API).
You can get the manifest with the digests for a tag with: `https://github.com/genuinetools/reg#get-a-manifest`
and delete a manifest with: `https://github.com/genuinetools/reg#delete-an-image`

**Comment by nlamirault** [comment]
In a future release : https://github.com/docker/distribution/pull/2169

**Comment by jstoja** [comment]
Still has some way to go. It's not yet merged and the last release of the registry is from Jul 20, 2017.
