### ISSUE TITLE
Would you know what this means?

### ISSUE THREAD

**Issue by gcstang** [genuinetools/reg#101]
Is there something I can use to debug this further?
I haven't found much in the way of this error online.
I have:
docker: 18.03.1.ce-1.el7.centos
registry:latest
reg: version v0.14.1, build d25a2c8
clair:latest from your Dockerfile.clair

*UPDATED*
I have the registry up and running as well as the registry command line tool working
Here is the actual command line I'm running and full output (some things are changed to hide personal details).
`r.host.com is a publicly accessible domain via a reverse proxy 'traefik'
main.host.com is where all my docker runs and is an internal system at 192.168.2.112

reg is an alias for this:
docker run --rm --name reg -p 8089:8089/tcp jessfraz_reg -d -u myuser -p mysecretpassword
Also of note: r.host.com/wx is my pushed image to my registry.

\# reg -d -k vulns --clair http://main.host.com r.host.com/wx
2018/06/26 19:00:26 registry.ping url=https://r.host.com/v2/
2018/06/26 19:00:27 registry.manifests uri=https://r.host.com/v2/wx/manifests/latest repository=wx ref=latest
2018/06/26 19:00:27 registry.registry resp.Status=200 OK
2018/06/26 19:00:27 registry.token url=https://r.host.com/v2/wx/blobs/sha256:ff3a5c916c92643ff77519ff...
2018/06/26 19:00:27 clair.layers.post url=http://main.host.com/v1/layers name=sha256:ff3a5c916c92643ff...
2018/06/26 19:00:27 clair.layers.post req.Body={"Layer":{"Name":"sha256:ff3a5c916c92643ff...","Path":"https://r.host.com/v2/wx/blobs/sha256:ff3a5c916c92643ff...","Headers":{"Authorization":"Basic Z2NyZWd1c2...="},"Format":"Docker"}}
2018/06/26 19:00:27 clair.layers.post resp.Status=404 Not Found
time="2018-06-26T19:00:27Z" level=fatal msg="json: cannot unmarshal number into Go value of type clair.layerEnvelope"`

**Comment by jstoja** [comment]
Hello @gcstang
Without more context it'll be hard to help you.
Have you tried to run clair using this guide: https://github.com/coreos/clair/blob/master/Documentation/running-clair.md#local ?

**Comment by gcstang** [comment]
@jstoja you're right sorry about that, added all my notes.

**Comment by jstoja** [comment]
I just tried to reproduce and I get that when I'm using `quay.io/repository/coreos/clair-git` image which is using the master branch, with the new api (v3).
If I use the latest of `quay.io/repository/coreos/clair`, I get the v2.0.3 with the v1 API which is answering fine.
I've just tried this with master:
```
./reg -d vulns --clair http://localhost:6060 r.j3ss.co/reg
...
 clair.layers.post resp.Status=404 Not Found
FATA[0001] json: cannot unmarshal number into Go value of type clair.layerEnvelope
```

And with v2.0.3:
```
./reg -d vulns --clair http://localhost:6060 r.j3ss.co/reg
...
 clair.layers.get url=http://localhost:6060/v1/layers/sha256:f8458bbe6820d7a48f13e1cd3c2f59cc73a9d6b0aedf26044689613592711a55?features=true&vulnerabilities=true name=sha256:f8458bbe6820d7a48f13e1cd3c2f59cc73a9d6b0aedf26044689613592711a55
 clair.clair resp.Status=200 OK
```

It's sad that `clair` has no `--version` or something similar that would have helped here... You can try to check the image being used though.

**Comment by gcstang** [comment]
@jstoja that was it, thank you
