### ISSUE TITLE
reg-server exits after ping to docker registry

### ISSUE THREAD

**Issue by mabunixda** [genuinetools/reg#11]
I tried to run you r.j3ss.co/reg-server with following command:
`docker run --rm r.j3ss.co/reg-server -d -r r.nitram.at:5000  --username $REG_USER --password $REG_PWD`

the output is
> 2017/03/15 13:29:01 registry.ping url=https://r.nitram.at:5000/v2/

And exit code 0 ... i tried to read your code through but i was not able to come to a solution.
When i restart the registry without htpasswd authentication the reg-server starts ... 

When i use the reg command ( r.j3ss.co/reg ) i get the following error message:
> Get https://r.nitram.at:5000/v2/: malformed auth challenge header: 'Basic realm="r.nitram.at"'

A docker login r.nitram.at:5000 works fine and also pulls and pushes are working

**Comment by jessfraz** [comment]
this is the same issue as #10 so I will close this one and we can continue the conversation there
