### ISSUE TITLE
Not delete images

### ISSUE THREAD

**Issue by DmitriyMurzin** [genuinetools/reg#114]
Command `reg rm local.repo/app:1.2.3` not working(
Please add remove command.

**Comment by jessfraz** [comment]
This isn't helpful I need more information like what is not working have you ran it in debug mode

**Comment by jessfraz** [comment]
Please paste the output here

**Comment by nlamirault** [comment]
Like #100

**Comment by jessfraz** [comment]
closing as dup of #100
