### ISSUE TITLE
Deleting images

### ISSUE THREAD

**Issue by defund** [genuinetools/reg#122]
Where do I find the sha256 hash that the rm command uses to delete an entire image?

**Comment by m4x2x4m** [comment]
running command reg manifest [registry]/[repo]:[tag] | grep sha256

**Comment by m4x2x4m** [comment]
but with latest release i have a problem with deleting images from registry , reg rm show message With Deleting of image, but after garbage-collect nothing changes

**Comment by ShashankYadav** [comment]
Having this issue with the registry cli for deletion as well, nayra123's PR seems to fix this issue. Requesting @jessfraz to please take a look at PR#123 `https://github.com/genuinetools/reg/pull/123`.

**Comment by jessfraz** [comment]
sorry for the delay, thanks for fixing!
