### ISSUE TITLE
reg docker image repository

### ISSUE THREAD

**Issue by mvillarejo** [genuinetools/reg#128]
Hello!

I'd like to run this application within docker compose but I'm unable to find it in docker hub, are you uploading it somewhere? it'll be great to have it so I can use it directly rather than building locally before use.

Thank you!

**Comment by jessfraz** [comment]
yes it is at jess/reg and r.j3ss.co/reg :) thanks! if youd like to make a PR to add that to the readme that would be great :)

**Comment by mvillarejo** [comment]
great! thanks
