### ISSUE TITLE
ManifestV2 will return a version 1 schema

### ISSUE THREAD

**Issue by rikkuness** [genuinetools/reg#147]
If I call `r.ManifestV2()` against a repo that has a version 1 manifest schema, the method doesn't err out at https://github.com/genuinetools/reg/blob/master/registry/manifest.go#L68-L71 the JSON unmarshals okay and is just empty minus having `mf.Versioned.SchemaVersion: 1`.

This causes some other weird things like if you call a Clair scan against a V1 manifest it doesn't fallback to the `ManifestV1` call and the V2 call didn't error, instead the scan says there was no non-empty layers.

**Comment by jessfraz** [comment]
closed buy #148
