### ISSUE TITLE
Static UI Server doesn´t work because of false value in "registry.manifests uri"

### ISSUE THREAD

**Issue by GEownt** [genuinetools/reg#154]
Hello,

I have a problem, if i try to start a static UI server fot a registry i can´t see any vulnerabilities.
The value of "repository" is false, I am not sure if this is a bug or only I got this issue...

My repositories are named like this: "angular-module" or "java-backend", etc.
In vendor/github.com/docker/docker/registry/session.go on line 328 - 335 happens sth. like this:

    func (r *Session) GetRemoteTag(registries []string, repositoryRef reference.Named, askedTag string) string, error) {
	repository := reference.Path(repositoryRef)

	if strings.Count(repository, "/") == 0 {
		repository = "library/" + repository
	}

and in registry/manifest.go on line 18,50,64 and 78 there is this:

    uri := r.url("/v2/%s/manifests/%s", repository, ref)

So at the end the request looks like this:
> uri=https://my-registry.my.company:443/v2/library/angular-module/manifests/latest

But the request should look like this to work:
> uri=https://my-registry.my.company:443/v2/angular-module/manifests/latest

Is there any option to change this? Or is this if statement useless?

Im using the official Docker Registry with Version 2.6.2

**Comment by jessfraz** [comment]
ah this is because it's against the docker hub registry so the image gets parsed as library since it thinks you are looking for the official image :) i will look into a fix

**Comment by jessfraz** [comment]
but by default this really doesnt work well with the official docker registry (hub)

**Comment by jessfraz** [comment]
actually this should be fixed for all private registries with the latest version as well :)
