### ISSUE TITLE
Proposal: support for passing context in registry calls

### ISSUE THREAD

**Issue by jesstracy** [genuinetools/reg#162]
It would be awesome if we could add methods that allow passing a context into registry calls like HasLayer, UploadLayer, etc. - for example:
```go
func (r *Registry) UploadLayer(repository string, digest reference.Reference, content io.Reader) error {
    // ...
}

func (r *Registry) UploadLayerWithContext(ctx context.Context, repository string, digest reference.Reference, content io.Reader) error {
    // ...
}
```
would this be something you'd consider merging if I made a PR? thanks!

**Comment by jessfraz** [comment]
you can change the API to do this without adding a new function i will just bump the version for those importing it to update ;) then it's cleaner
