### ISSUE TITLE
Improve index.html

### ISSUE THREAD

**Issue by majst01** [genuinetools/reg#19]
Hi,

we have ~9000 rows in the resulting index.html because we have a lot of images with a lot of tags each.
Loading index.html takes forever because its 8mb in size.

I would like to reduce the content of the index.html to only list all images which are links to a page per image which will list all tags of this image. The reference to the vulns will be located there as well.

@jessfraz what do you think ?

**Comment by ggirtsou** [comment]
Let me chime in if I may, do you mean to split the results in multiple HTML pages? Like `index.html`, `results-1.html`, ...

**Comment by jessfraz** [comment]
You can build in pagination I just didn't need it

**Comment by majst01** [comment]
I can imagine to serve index.html dynamically, should be fast if it only represents the catalog and the tags per image are rendered to a static page for every image.

**Comment by majst01** [comment]
I open a PR to address this issue here #21

**Comment by majst01** [comment]
merged.
