### ISSUE TITLE
reg uses incorrect registry endpoint

### ISSUE THREAD

**Issue by mtibben** [genuinetools/reg#20]
Seems like reg is munging the registry endpoint when the docker config registry URL contains a path

```bash
$ cat ~/.docker/config.json
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "*******"
		}
	}
}

$ reg --debug manifest library/ubuntu:trusty
2017/04/05 20:57:51 registry.ping url=https://index.docker.io/v1/v2/
2017/04/05 20:57:52 registry.manifests uri=https://index.docker.io/v1/v2/library/ubuntu/manifests/trusty repository=library/ubuntu ref=trusty
```

**Comment by jessfraz** [comment]
This only works with v2 registries it will not work with v1

**Comment by mtibben** [comment]
Yep I realise that, however `docker login` onto docker hub results in a `~/.docker/config.json` file that looks like the above (with the `/v1/`) even though docker hub also supports v2. Not sure if the docker cli client is stripping this, or actually using the hub v1 API.

Anyway my workaround is to just strip the `v1` manually before using `reg`
