### ISSUE TITLE
github.com/docker/distribution/digest moved to github.com/opencontainers/go-digest

### ISSUE THREAD

**Issue by mabunixda** [genuinetools/reg#6]
Seems the dep moved to github.com/opencontainers/go-digest

**Comment by jessfraz** [comment]
The dependencies are vendored this should not be an issue all tests pass

**Comment by mabunixda** [comment]
damn missed that :(

**Comment by mabunixda** [comment]
i miss something else .. just clone the repo and make does not work ...
