### ISSUE TITLE
Travis builds fail for tip version - use stable instead

### ISSUE THREAD

**Issue by pawelprazak** [genuinetools/reg#66]
All recent builds fail in a weird way:

```
$ staticcheck $(go list ./... | grep -v vendor)
/home/travis/gopath/src/github.com/jessfraz/reg/vendor/github.com/docker/docker/registry/session.go:572:32: cannot use tarsumLayer (variable of type github.com/jessfraz/reg/vendor/github.com/docker/docker/pkg/tarsum.TarSum) as io.Reader value in argument to io.TeeReader: missing method Read
couldn't load packages due to errors: github.com/jessfraz/reg/vendor/github.com/docker/docker/registry
The command "staticcheck $(go list ./... | grep -v vendor)" exited with 1.
```

I was not able to reproduce it locally. But from what I can gather, `tip == master`:
https://github.com/travis-ci/gimme/issues/110
https://github.com/travis-ci/travis-build/commit/b114b18b3e762b9661d080eca2b5942d70b39c34#diff-fe52d3b67e8fe283d39c20d2b87d82f8

Moreover, [the docs](https://docs.travis-ci.com/user/languages/go) doesn't mention `tip` at all, there's only `1.x` and `master`.

So IMHO something [like this](https://github.com/google/go-cmp/issues/13) would be better / more stable, e.g.:

```
...
go:
  - 1.x
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
...
    on:
      go: 1.x
...
```

**Comment by pawelprazak** [comment]
I've reproduced it locally:
```
docker run --rm -v "$PWD":/go/src/github.com/jessfraz/reg --workdir /go/src/github.com/jessfraz/reg -v /tmp:/tmp reg-gimme:latest make init staticcheck
go version devel +07f0f09563 Fri Feb 16 15:37:57 2018 +0000 linux/amd64
+ init
go get -u honnef.co/go/tools/cmd/staticcheck
+ staticcheck
/go/src/github.com/jessfraz/reg/vendor/github.com/docker/docker/registry/session.go:572:32: cannot use tarsumLayer (variable of type github.com/jessfraz/reg/vendor/github.com/docker/docker/pkg/tarsum.TarSum) as io.Reader value in argument to io.TeeReader: missing method Read
couldn't load packages due to errors: github.com/jessfraz/reg/vendor/github.com/docker/docker/registry
```

With a custom `gimme` image set to `tip` version.

**Comment by pawelprazak** [comment]
I've tried the `1.x` version with mixed results: https://travis-ci.org/pawelprazak/reg/jobs/342529887

Deployment hasn't triggered:
> Skipping a deployment with the releases provider because this is not on the required runtime

**Comment by pawelprazak** [comment]
Using the undocumented `stable` version (resolved to go1.9.4) gives the expected result:
https://travis-ci.org/pawelprazak/reg/jobs/342534715

**Comment by pawelprazak** [comment]
@jessfraz any thoughts on this?

**Comment by jessfraz** [comment]
Thanks for going into so much detail, ya this happening on like 30 of my projects because I share the same travis config. I will fix

**Comment by jessfraz** [comment]
fixed by https://github.com/jessfraz/reg/commit/533d292bfbb0de9e7763e5222a40ba744b5006ae

**Comment by pawelprazak** [comment]
I hate when CI is red ;) also reverse-engineering is so much fun
