### ISSUE TITLE
checking out source code to case insensitive filesystem results in error

### ISSUE THREAD

**Issue by daniel-garcia** [genuinetools/reg#74]
Checking out this repo to a case insensitive filesystem (like OSX HFS+) results in an error during checkout. This is not a problem for development but it is a problem for vendoring reg into other projects. MR inbound.

**Comment by jessfraz** [comment]
I need to fix this for all my repos, I am insane linux user :)

**Comment by jessfraz** [comment]
I changed this in a different way for all my repos, sorry, thanks!
