### ISSUE TITLE
Container not working on run

### ISSUE THREAD

**Issue by dawaj71** [genuinetools/reg#84]
Hello,

I did a gitclone to get your files then i wanted to use docker build and docker run to run reg in a container but the container stay exited.

Do you have a command to let the container up ?

by the way i tried docker container run reg:latest vulns --clair https://localhost:6060 ubuntu its not working

i have a clair container in local

**Comment by jessfraz** [comment]
can you add debug and localhost:6060 needs to be in the containers network, not your hosts network fwiw, and you might want to mount $HOME/.docker into the container for auth
