### ISSUE TITLE
reg ls should provide lexicographical ordered output

### ISSUE THREAD

**Issue by mrueg** [genuinetools/reg#98]
As a user I would expect `reg ls` to behave similar to `ls` and provide a lexicographically ordered output.
Currently the output of `reg ls` has no visible order.

**Comment by jessfraz** [comment]
Are you on the latest version it's alphabetical

**Comment by mrueg** [comment]
Even better, sorry for the noise then. :) Unfortunately, I'm seeing this regression in 0.14.0 https://github.com/genuinetools/reg/issues/97
